name: Neo4J Setup Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
    - uses: actions/checkout@v3

    - name: Install required dependencies
      run: |
        apt-get update
        apt-get install -y wget gnupg systemd

    - name: Install Neo4j
      run: |
        curl -fsSL https://debian.neo4j.com/neotechnology.gpg.key | gpg --dearmor -o /usr/share/keyrings/neo4j.gpg
        echo "deb [signed-by=/usr/share/keyrings/neo4j.gpg] https://debian.neo4j.com stable latest" | tee /etc/apt/sources.list.d/neo4j.list
        apt-get update
        apt-get install -y neo4j

    - name: Start Neo4j
      run: |
        neo4j start
        sleep 10  # Wait for Neo4j to start

    - name: Set up Mamba
      uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge,defaults
        channel-priority: strict
        activate-environment: ldf-tests
        environment-file: environment.yml
        auto-activate-base: false
        miniconda-version: "latest"

    - name: Install mamba
      shell: bash -l {0}
      run: |
        conda install -n base -c conda-forge mamba

    - name: Set Neo4j environment variables
      run: |
        echo "NEO4J_TESTING_DB_URI=bolt://localhost:7687" >> $GITHUB_ENV
        echo "NEO4J_TESTING_USERNAME=neo4j" >> $GITHUB_ENV
        echo "NEO4J_TESTING_PASSWORD=neo4j" >> $GITHUB_ENV

    - name: Ensure systemd users and groups
      run: |
        getent passwd systemd-network || useradd -r systemd-network
        getent group systemd-journal || groupadd -r systemd-journal
        getent group systemd-resolve || groupadd -r systemd-resolve
        getent passwd systemd-resolve || useradd -r -g systemd-resolve systemd-resolve

    - name: Run tests
      shell: bash -l {0}
      run: |
        mamba run -n ldf-tests python -m pytest opengin/tests/neo4j/test_local_instance.py -v 